server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: author-service
          uri: lb://AUTHOR-SERVICE
          predicates:
            - Path=/authors/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
