server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: author-service
          uri: 'lb://AUTHOR-SERVICE'
          predicates:
            - Path=/author-service/**
          filters:
            - StripPrefix=1
        - id: book-service
          uri: 'lb://BOOK-SERVICE'
          predicates:
            - Path=/book-service/**
          filters:
            - StripPrefix=1
        - id: rating-service
          uri: 'lb://RATING-SERVICE'
          predicates:
            - Path=/rating-service/**
          filters:
            - StripPrefix=1
        - id: author-actuator
          uri: 'lb://AUTHOR-SERVICE'
          predicates:
            - Path=/author-service/actuator/**
          filters:
            - StripPrefix=1
        - id: book-actuator
          uri: 'lb://BOOK-SERVICE'
          predicates:
            - Path=/book-service/actuator/**
          filters:
            - StripPrefix=1
        - id: rating-actuator
          uri: 'lb://RATING-SERVICE'
          predicates:
            - Path=/rating-service/actuator/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka-server:8761/eureka'
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: author-service
        url: /author-service/v3/api-docs
      - name: book-service
        url: /book-service/v3/api-docs
      - name: rating-service
        url: /rating-service/v3/api-docs
